version: "3"

services:
  postgres_test:
    container_name: postgres_test
    image: postgres:alpine
    env_file: .env.test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: trz